import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import { QueryWrapper } from "../layouts/query.wrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Tech Comrade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <NextTopLoader
          color="linear-gradient(to right, rgb(134, 239, 172), rgb(59, 130, 246), rgb(147, 51, 234))"
          speed={800}
          zIndex={9999}
        />
        <QueryWrapper>{children}</QueryWrapper>
        <Toaster richColors />
      </body>
    </html>
  );
}
